name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository name
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
         distribution:'temurin' 
         java-version:'21' 
         cache:'maven'
      - name: Build with Maven
        run: |## mehrere Zeilen mvn -B -DskipTests package
          echo "--------------------"
          cp src/main/docker/Dockerfile target
          docker build --tag ghcr.io/${{github.actor}}/backend:latest ./target/
          docker push ghcr.io/${{github.actor}}/backend:latest
          ls -lh target